name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get install libclang-dev

      - uses: actions/checkout@v2

      - uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: |
          cargo build --workspace --all-features --benches --bins --lib --examples --verbose

  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get install libclang-dev

      - uses: actions/checkout@v2

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - uses: giraffate/clippy-action@v1
        with:
          reporter: 'github-pr-review'
          github_token: ${{ secrets.GITHUB_TOKEN }}

  format:
    name: Rustfmt
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - uses: mbrobbel/rustfmt-check@master
        if: github.event_name == 'pull_request'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          mode: review

      - if: github.event_name == 'push'
        run: |
          cargo fmt --all -- --check

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get install libclang-dev

      - uses: actions/checkout@v2

      - uses: dtolnay/rust-toolchain@stable

      - name: Run Tests
        run: |
          cargo test --workspace --all-features --verbose

  dependabot:
    runs-on: ubuntu-latest
    needs: [ clippy, format, build, tests ]

    permissions:
      pull-requests: write
      contents: write

    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
